title:              YerBlog
email:              your-email@example.com
description:        A Jekyll Blog Theme by jinyery
author:             jinyery
baseurl:            ""
url:                "https://blog.yer.xyz"

# Social Profiles
zhihu_username:     jinyery
weibo_username:     jinyery
github_username:    jinyery
twitter_username:   jinyery
facebook_username:  
linkedin_username:  
instagram_username: 

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

# Website registration number in Chinese Mainland.
icp: 

# Add your custom nav item to the nav bar.
# Note that this item cannot be an array, as our philosophy is restraint.
special_nav_item: 
special_nav_link: 

# A Lightweight Blog Comment System Based on Github Issues: Utterances.
# You can refer to https://utteranc.es/
utterances_repo: 
utterances_label:   
utterances_theme:   # default to github-light
utterances_issue_term: # default to pathname